CREATE TABLE notes(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    title VARCHAR(255) DEFAULT NULL,
    mimeContentType VARCHAR(255) DEFAULT NULL,
    content BLOB DEFAULT NULL,
    courseID VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE comments (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    content VARCHAR(255) DEFAULT NULL,
    courseID VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE users (
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    PRIMARY KEY (username)
);

CREATE TABLE userRoles(
    roleId INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    username VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (roleId),
    FOREIGN KEY (username) REFERENCES users (username)

)